name = "october-subscribe"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://www.october-academy.com,https://october-academy.com,https://october-landing.pages.dev,http://localhost:3000"
KAKAO_CHAT_URL = "https://open.kakao.com/o/pUJ4dbai"
TEMPLATES_URL = "https://drive.google.com/drive/folders/1VBJrhcU-jRULmgkReH6xd2TDUeMTQYov?usp=sharing"
INFLEARN_GOOGLE_SHEET_ID = "1x02W1pW8a8MS1pWkXpJ6gZGFQmQnj4oyG78QoS_s71M"
LEAGUE_GOOGLE_SHEET_ID = "1ce6g953F8iY9_0uB18qbjt6CHLdoCY3a6spxk3XT6kk"
